### ISSUE TITLE
Event Images are not centered

### ISSUE THREAD

**Issue by hussamsh** [mostafa-abdullah/kheir-blogger#128]
When opening an event image from the gallery, the image is not centered but rather it's bottom half is cropped at the bottom of the screen , scrolling up and down or centering the page before opening the image doesn't solve the problem.
The image offset depends on the scroll state of the page

**Comment by Omarkojak** [comment]
@mostafa-abdullah checked that and it worked with other people idk why it didn't work with hussam :D

**Comment by AhmadElsagheer** [comment]
@hussamsh I have seen your problem and it depends on the size and dimensions of the photo. It needs more handling but no need for that as it is a front-end issue
