### ISSUE TITLE
Delete post event 

### ISSUE THREAD

**Issue by BaherAbdelmalek** [mostafa-abdullah/kheir-blogger#133]
button in front of the posts in the events should not viewed to the volunteer

**Comment by Omarkojak** [comment]
@AhmadElsagheer and @baher10 
Elbuttons bt3 delete post msh bezhr 3.er lel organization eli 3mla elevent w account bt3 eladmin eli hwa (ahmad@gmail.com) in our case mbezhrsh lelvalidators 7ta et2kdo e7teaty w hal han7tag eno validator ymkn yshel post wla ?

**Comment by Omarkojak** [comment]
However if an admin try to delete the post it will fail !!

**Comment by Omarkojak** [comment]
This issue will be for deleting post bug for admins
