### ISSUE TITLE
Admin delete events and photos of an event

### ISSUE THREAD

**Issue by khlyy** [mostafa-abdullah/kheir-blogger#134]

**Comment by Omarkojak** [comment]
@AhmadElsagheer @khlyy hwa elmfrod ynf3 ydelete post

**Comment by Omarkojak** [comment]
admin already can delete posts this issue willbe for deleting photos from the gallery and event

**Comment by AhmadElsagheer** [comment]
##### Edits for event deletion
- `destroy` function of EventController must be accessible by admins only. An admin can delete an event permanently so it is not added to the cancelled events.
- `cancel` function is needed for an organization to cancel its event. For sure, it will affect the cancellation rate as the event is trashed not deleted.
- When an organization is deleted all its upcoming events are permanently deleted. However, its past events must be accessible and perhaps with no host name.

**Comment by AhmadElsagheer** [comment]
Notifications are sent in case of destroyed/cancelled events. Both notifications have the same type "cancelled"
