### ISSUE TITLE
API | cannot access images 

### ISSUE THREAD

**Issue by hussamsh** [mostafa-abdullah/kheir-blogger#179]
I still can't access the gallery on the server , even from `/storage/app/db/gallery/event_id/photo_name` it downloads a file with an unknown extension.

**Comment by Omarkojak** [comment]
msh fahm asdk f anhy 7ta lma btupload wla btsave wla btadd elcaptions

**Comment by AhmadElsagheer** [comment]
They are saved without extensions on the server but they can be displayed properly

**Comment by hussamsh** [comment]
@Omarkojak  la2 ana 2asdy lama bahawel a get image mo3aina 

@AhmadElsagheer When I try it with the route given above it downloads a file with an unknown extension but after adding `.jpeg` extension as you said, it works !
Shouldn't the backend handle this and give me an image not a file that I have to convert ? also the libraries I use need a `jpeg` response to directly download and convert the image into bitmaps, and I think that downloading and then converting files will add unnecessary overhead to the app development process !

**Comment by AhmadElsagheer** [comment]
ok, I will look for a solution

**Comment by AhmadElsagheer** [comment]
Assume that the links you receive will have the extension included

**Comment by hussamsh** [comment]
I receive a file not a link , even adding `.jpeg` to route end doesn't work , and as I mentioned I don't manually convert files to images, I use libraries that does that for me and it needs the response to be a `jpeg` or any other image format file,  the backend should convert the files and then send me a URL to the location of the photo on the server (If done correctly , said URL should open a photo in the browser not download it)

**Comment by AhmadElsagheer** [comment]
Assuming development and running on localhost, it will be accessible through http://localhost:8000/storage/app/db/gallery/[event_id]/[returned_value]
It will open correctly in the browser.
This issue will be closed upon merging the corresponding pull request

**Comment by hussamsh** [comment]
The [returned_value] is the photo name ?

**Comment by AhmadElsagheer** [comment]
yes including the extension
