### ISSUE TITLE
Event Gallery

### ISSUE THREAD

**Issue by AhmadElsagheer** [mostafa-abdullah/kheir-blogger#71]
As an organization, I can add a gallery for an event and view it.

**Comment by Omarkojak** [comment]
m3lsh b2al so2al hwa elgallery we will use elidea eli mostafa 2alha en elimages tb2a 3ala amazon wla tb2a 3la folder f eldirectory bt3hom ?

**Comment by AhmadElsagheer** [comment]
mwdoo3 amazon lamma ykoon 3ndna deployment. All photos will be placed inside `public` folder. You will put photos in the following directory `public/db/gallery/event_id/photo_id`

**Comment by AhmadElsagheer** [comment]
@Omarkojak Update your issue in the boards

**Comment by Omarkojak** [comment]
so2al e7na han7tag nenotify elsers eli 3amla follow lelevent en photos were uploaded wla ?

**Comment by Omarkojak** [comment]
i want some help in adding captions only when i click on the photo elmoshkla dlw2ty en feh grbt asht3,l behom w7da eli 3aml beh elcommit eno elforeach after elclass bt3 blue-imp gallery dih kant btdisplay elphotos bs mkntsh b3rf add captions awl mclik 3la elsora btzhr k2nda slideshow bt2lb feh ymen w shemal 
elimplementation eltany eni a3ml elkalam dh gwa eltemplate eli kont b2lha mn elgithub repo bs elfkra en dih mzhrtlish elphotos asln :D
