### ISSUE TITLE
Start of Sprint 2

### ISSUE THREAD

**Issue by AhmadElsagheer** [mostafa-abdullah/kheir-blogger#72]
- For this sprint, we will be using **ZenHub** to track our progress instead of the spreadsheet.
  You will need to install ZenHub extension from here: https://www.zenhub.io/
- Since our project is not big, we will relate all our progress to our repo in gitHub using ZenHub in the following way:
1. All user stories are added as issues where each issue has:-
   a. **Title**: a short name for the user story. You will use this title for branch naming. Let's follow a convention: all letters will be lower case with spaces replaced by hyphens.
   b. **Description**: more details for the user story. It will be the first comment in the issue. Discussion about the user story will follow in the comments.
   c. **Pipeline**: showing the progress of the user story. You can find all phases in the _Boards_ tab.
   d. **Labels**: tags for the issues. User stories are tagged **feature** and maybe tagged **dependent** if there exists some user story that is not implemented yet and we will need to implement or integrate. You can see all available labels in the "Issues" > "Labels".
   e. **Milestone**: with start and due dates. Milestones are extremely helpful. You can filter Boards using a milestone. In addition, there is a **Burndown** tab in which we can keep track of the total points, points done, points remaining and everything about the milestone. Our current milestone is sprint 2 and the due date is 31/4/2016.
   f. **Estimate**: points assigned for the user story.
   g. **Assignee**: our superman/superwoman for this user story :sweat_smile: .
2. We will use issues for any further discussions. If you need to created a new issue, then do it, specify the labels and add it to the _new issues_ board. You have labels for bug, discussion, question, help wanted and other things.
3. You can stop receiving notifications about a certain issues from the page of that issue on the right side panel "unsubscribe". However, I don't recommend that.
4. You can reference any issue in any comment using the hash. For example, if the issue is numbered 64, then reference it as #64.
5. Any user story will be completed through one branch only. However, you may make more than one pull request for the same branch/user story if need.
6. Don't forget to update the progress of the user story in _Boards_.
7. All commits you do add to it a reference to the user story issue, so that commit will be reflected in the issue itself. For example, if you are working on user story #61, you may do something like: 
   
   > `$ git commit -m "#61 created locations table`
8. When making a pull request, start its name with the user story issue reference, then the user story name. For example, 
   
   > # 61 | Volunteer assign locations
9. You can find all user stories in **Issues**, the form will be sent to you very soon inshallah.

Keep Motivated! :smile: :smile:

**Comment by AhmadElsagheer** [comment]
Anyone who started working on their user stories: update the user story status in ZenHub boards

**Comment by AhmadElsagheer** [comment]
Please note that hyphen means a dash (-). Rename your branches with hyphens not underscores

**Comment by AhmadElsagheer** [comment]
Make only one pull request for the user story (when you are done with it) unless another user story depends on something in it. In such a case, you will make a special pull request for this thing. Otherwise, just push your progress on your remote branch and don't forget to reference your issue number in commits so I can easily track your progress

**Comment by AhmadElsagheer** [comment]
Anyone working on the user stories or the API: **You will need to pull from master before going on with your work**

**Comment by AhmedSoliman7** [comment]
Anyone working on a issue, please update it in the boards

**Comment by AhmadElsagheer** [comment]
So we are done with Sprint 2 :balloon: :balloon:
