### ISSUE TITLE
Gallery userstory

### ISSUE THREAD

**Issue by Omarkojak** [mostafa-abdullah/kheir-blogger#73]
i have a bug when after making migration for images then when  i use 
php artisan migrate 
it gives me this 
[PDOException]  
  SQLSTATE[HY000] [2002] Connection refused 
nas bt2ol 3.er elDB host le local host 3.ertha mfr2tsh brdo

**Comment by AhmadElsagheer** [comment]
Most probably, you are having a problem with either DB server hostname or password. **.env** file should contain both DB_HOSTNAME and DB_PASSWORD set to the values you use to login to your DB server either using phpmyadmin or through the terminal. Make sure they match the exact values (check for blanks)

**Comment by Omarkojak** [comment]
5alas done thanks ya sagheer

**Comment by AhmadElsagheer** [comment]
you're welcome
