### ISSUE TITLE
Organization API - POST Requests

### ISSUE THREAD

**Issue by AhmadElsagheer** [mostafa-abdullah/kheir-blogger#89]
Branch Name: `api-organization`
Functionalities:
1. Controller: `OrganizationAPIController`
   - OrganizatonController.update
   - OrganizationController.subscribe/unsubscribe
   - OrganizationController.block/unblock
   - OrganizationController.storeRecommendation
   - OrganizationController.viewRecommendations
- You should make user of `Services`. Check `VolunteerAPIController`. The main function will be implemented in the service and will be called by both normal and API controllers.
- In your pull request, write in the first comment `For issue #X` where X is this issue number

**Comment by omarradwan** [comment]
When I try to findOrFail($id), a query exception is thrown because there is no deleted_at column in organizations table. Is that related to the soft delete issue? What shall I do to fix this problem?

**Comment by AhmadElsagheer** [comment]
`php artisan migrate:refresh`

**Comment by omarradwan** [comment]
foll
